### ISSUE TITLE
Minor bug in R2D2Base

### ISSUE THREAD

**Issue by LouChao98** [ant-research/StructuredLM_RTDT#4]
https://github.com/ant-research/StructuredLM_RTDT/blob/58a178390143e742b174b59ee70586c66240e2cc/model/r2d2_base.py#L14-L17

The `input_dim` of `self.classifier` should be `config.hidden_size`(or `self.input_dim`) rather than `config.intermediate_size`(or `self.hidden_dim`).

This bug does not causes errors because `_tie_weights` sets the weight of `self.classifier` to the correct shape.

**Comment by imhuim982** [comment]
Thanks. We will fix it when we release the latest code for the self-interpretable symbolic-neural model.
